name = "voice-backend"
main = "index.js"
compatibility_date = "2025-03-01"

[[d1_databases]]
binding = "DB"
database_name = "voice-d1"
database_id = "70869738-3761-479c-86fc-908d66acf81c"   # ← get from wrangler d1 list
